defaults: ./performance/grpo-qwen3-30ba3b-4n8g.yaml

grpo:
  num_prompts_per_step: 16
  num_generations_per_prompt: 8
  max_num_steps: 50
  val_period: 1000

checkpointing:
  checkpoint_dir: results/grpo-qwen3-30ba3b-4n8g-megatron-zmq-noncolocated

policy:
  train_global_batch_size: 128
  generation_batch_size: 16
  max_total_sequence_length: 2048
  sequence_packing:
    train_mb_tokens: 2048
    logprob_mb_tokens: 4096
  megatron_cfg:
    activation_checkpointing: true
    env_vars:
      PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True
  generation:
    refit_transport: vllm_zmq_sparse
    delta_compression:
      encoding: xor
      sparse_bucket_size_bytes: 536870912
    colocated:
      enabled: false
      resources:
        gpus_per_node: 8
        num_nodes: 2

logger:
  log_dir: logs/grpo-qwen3-30ba3b-4n8g-megatron-zmq-noncolocated
  wandb:
    project: nemo-rl-refit
    name: grpo-qwen3-30ba3b-4n8g-megatron-zmq-noncolocated
