defaults: ../../grpo_math_1B_sglang.yaml
grpo:
  max_num_steps: 450
checkpointing:
  checkpoint_dir: results/grpo-qwen2.5-math-1.5b-instruct-2n8g-megatrontp1-sglang-noncolocated
policy:
  model_name: Qwen/Qwen2.5-Math-1.5B-Instruct
  tokenizer:
    name: Qwen/Qwen2.5-Math-1.5B-Instruct
  optimizer: null
  megatron_cfg:
    enabled: true
    scheduler:
      lr_warmup_iters: 50
  dtensor_cfg:
    enabled: false
  dynamic_batching:
    enabled: true
  sequence_packing:
    enabled: false
  make_sequence_length_divisible_by: 1
  generation:
    max_new_tokens: 512
    colocated:
      enabled: false
      resources:
        gpus_per_node: 8
        num_nodes: 1
    sglang_cfg:
      tp_size: 2
      sglang_server_config:
        num_gpus: 8
      sglang_router_config:
        use_distributed_post: true
data:
  max_input_seq_length: 512
logger:
  log_dir: logs/grpo-qwen2.5-math-1.5b-instruct-2n8g-megatrontp1-sglang-noncolocated
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-qwen2.5-math-1.5b-instruct-2n8g-megatrontp1-sglang-noncolocated
cluster:
  gpus_per_node: 8
  num_nodes: 2
